all: MalliavinNotes.pdf

MalliavinNotes.pdf: MalliavinNotes.tex
	pdflatex MalliavinNotes.tex
	pdflatex MalliavinNotes.tex

clean:
	rm -f *.aux *.log *.out *.toc *.bbl *.blg *.fls *.fdb_latexmk MalliavinNotes.pdf
