MAIN = Adv_Tops_in_ML

.PHONY: all clean

all:
	pdflatex -interaction=nonstopmode $(MAIN).tex
	pdflatex -interaction=nonstopmode $(MAIN).tex
	rm -f *.aux *.log *.toc *.out

clean:
	rm -f *.aux *.log *.toc *.out *.pdf
